### ISSUE TITLE
Bug: Right click event triggers screen drag event listener

### ISSUE THREAD

**Issue by stephwestgarth** [SSENSE/vue-carousel#249] opened 2018-07-23 02:03 UTC
Hi there,

Interesting bug here; if you right click on an element in a slide, when you close the dialog, it will react as if you are trying to do a touch move event. It doesn't matter if you click any option like "open in new tab" or just somewhere else on the page, it doesn't stop registering the click and treats it like a touch move event. Demonstrate-able on the Vue Carousel demo page: https://ssense.github.io/vue-carousel/

Steps to reproduce:
1. Right click any item on the carousel
2. Hit any option within the menu, or press the escape key.
3. Move your mouse. Watch the carousel follow your mouse.

Obviously not a huge deal, but very weird behaviour that'd be great to get fixed!

**Comment by quinnlangille** [comment] 2018-07-23 15:50
That's definitely a weird bug lol seems like it would be a good first fix for a contributor - I'll flag it now! The issue is likely just an conditional that is too broad somewhere, or an improperly destroyed event listener.

Thanks for reporting! :~)

**Comment by utkarshnag** [comment] 2018-09-02 09:41
@quinnlangille has this issue been fixed? I'm unable to reproduce the bug.

**Comment by quinnlangille** [comment] 2018-09-02 23:38
Yeah I was able to reproduce just now on the https://ssense.github.io/vue-carousel/ homepage

**Comment by quinnlangille** [comment] 2019-03-21 21:07
This has been released in 0.18.0 :octocat: Thanks @nandaleite for the contribution!

**Closed by quinnlangille** 2019-03-21 21:07 UTC
Labels: bug, good first issue, help wanted
