### ISSUE TITLE
Question: Is Vue-Carousel production ready?

### ISSUE THREAD

**Issue by lakshmananmurugesan** [SSENSE/vue-carousel#276] opened 2018-09-01 18:04 UTC
@HugoPelletier @coljung @VinceG @YAAK @yannbr Hi Guys, I have a question. This repository looks promising with number of downloads and star ratings, good options and so want to use it. Is this production ready? I saw readme that its on alpha-state. Can you please clarify its stability?

**Comment by VinceG** [comment] 2018-09-01 18:09
@lakshmananmurugesan we use it in production. The only issue we have which is not a bug but a feature missing is the the ability to drag the carousel back and forth like you would on a mobile device but on desktop. 

Other than that we had no issues since we launched.

**Comment by quinnlangille** [comment] 2018-09-01 19:51
Hey @lakshmananmurugesan, while the repo is still in alpha (there is lots of development happening) we're approaching a v1 release, in which we will remove the alpha disclaimer from the readme.

 In the meantime, lots of people (including myself) use the carousel in production. The disclaimer is mostly there just to let developers know the API spec will usually change frequently (mostly just additions).

**Comment by lakshmananmurugesan** [comment] 2018-09-02 05:00
@VinceG @quinnlangille Thanks for the quick turn up and clarifications. This helps me!

**Comment by its-rj** [comment] 2018-09-04 11:04
@quinnlangille Concerning production ready: Is there a rough roadmap which features will be included next? I'm asking since I got the request to find a Vue based slider that is flexible enough to realize stuff like these:
https://www.marc-cain.com/Inspiration/Specials/Look-of-the-Month/
https://www.marc-cain.com/Inspiration/Herbst-Winter-2018/Kampagne/Marc-Cain-Collections/

**Comment by quinnlangille** [comment] 2018-09-04 15:05
Hey @its-rj, we have a tag for issues on our roadmap -> https://github.com/SSENSE/vue-carousel/issues?q=is%3Aopen+is%3Aissue+label%3Aroadmap

They're what we're currently prioritizing, but they're also pretty large. So ETA is difficult to evaluate

**Comment by its-rj** [comment] 2018-09-04 17:03
Thanks, @quinnlangille. Sorry that I haven't noticed it.

**Comment by pushpitab** [comment] 2018-09-09 15:14
Does the carousel support youtube video link?

**Comment by quinnlangille** [comment] 2018-09-10 14:26
@pushpitab right now it will support a basic URL to a video in the source. Once we have an answer for #172 it will support basically anything, in case you want to add a custom video component or something like that

**Comment by quinnlangille** [comment] 2018-09-18 17:06
Since the initial questions been answered and we haven't had any chat in a while, going to close this. Feel free to open another issue if anyone has any questions :octocat:

**Closed** 2018-09-18 17:07 UTC
Labels: question
