### ISSUE TITLE
Bug: Warning and rendering issue with Nuxt.js SSR

### ISSUE THREAD

**Issue by rohitpal99** [SSENSE/vue-carousel#31] opened 2017-03-03 09:17 UTC
Please suggest how to use with Vue SSR.
I am trying to integrate this with VueJS's framework [Nuxt.js](https://github.com/nuxt/nuxt.js)

```
import Vue from 'vue'
if(process.BROWSER_BUILD) {
    const VueCarousel = require('vue-carousel');
    VueCarousel.default.install(Vue)
}
```

I am getting this 

> vue.runtime.common.js:521 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

Although I am able to make it work in dev mode, regardless of the warning.
On production mode **vue-carousel** doesn't work and doesn't show images at all.
![image](https://cloud.githubusercontent.com/assets/7090592/23545214/5b5e34b8-0020-11e7-96dd-d1d148147b59.png)

Please suggest.

**Comment by toddlawton** [comment] 2017-03-03 16:06
Hi @rohitpal99 

I haven't worked with Nuxt.js before, I currently use this carousel in a SSR environment very similar to [this one](https://github.com/vuejs/vue-hackernews-2.0) without any issues. Looking for help from anybody who can investigate with Nuxt.

**Comment by gabrielmancini** [comment] 2017-04-19 19:08
+1

**Comment by royscheeren** [comment] 2017-05-04 06:34
I'm having the exact same issue. Using
```
if (process.browser) {
  const VueCarousel = require('vue-carousel')
  VueCarousel.default.install(Vue)
}

to make the carousel globally available but indeed receiving the same warning when actually using it.

**Comment by DiederikvandenB** [comment] 2017-05-04 12:58
I am using this plugin with Vue and Nuxt too. @royscheeren, I am implementing it as a plugin with `{src: '~plugins/vue-carousel.js', ssr: false},` in the `nuxt.config.js` file and with 

``` js
import Vue from 'vue';
import VueCarousel from 'vue-carousel';

Vue.use(VueCarousel);
```

However, I indeed receive the same error.

**Comment by DiederikvandenB** [comment] 2017-05-24 08:36
Is there anyone working on this issue? I would love to solve it myself but I do not really know where to start.

**Comment by jakeknight** [comment] 2017-07-11 15:02
Are you importing vue-carousel in any of your files? I've managed to get this working.

I added a vue-carousel.js file to the plugins folder, and then in my nuxt config folder `{ src: '~plugins/vue-carousel.js', ssr: false }`

and inside my vue-carousel.js folder I just have 

```
import Vue from 'vue';
import VueCarousel from 'vue-carousel';

Vue.use(VueCarousel);
```

I was trying to import the carousel which was breaking my build, however the plugin is available to use globally if installed in this way ^^

**Comment by dieguezz** [comment] 2017-08-02 11:22
I solved it by: 

`// nuxt.config.js`
```
plugins: [{ src: '~/plugins/carousel', ssr: false }],
```
`// plugins/carousel.js`
```
import Vue from 'vue'
import { Carousel, Slide } from 'vue-carousel'

Vue.component('carousel', Carousel)
Vue.component('slide', Slide)
```
Hope it helps!

**Comment by iamdubx** [comment] 2017-08-07 20:11
@dieguezz you will still have error in console, what are you talking about?

**Comment by dieguezz** [comment] 2017-08-07 22:12
@iamdubx That just worked for me, without messages in console. Maybe your problem is in another place, or i got something different which i forgot to mention (Like nuxt.js version or something but i dont think so). Anyway i am not using this plugin anymore, i made my own component because its a really simple feature.

Sorry if that does not help much..

**Comment by andreasvirkus** [comment] 2017-08-09 13:18
@toddlawton I'm also working with Vue's native SSR (similarly to you, based also off of HN2.0 example) and am wondering how you managed to import it conditionally? Currently if setting up as the guide/examples show us to, I run into the following errors (server-side):
```
 ReferenceError: document is not defined
    at r (project/node_modules/vue-carousel/dist/vue-carousel.min.js:6:2155)
    at a (project/node_modules/vue-carousel/dist/vue-carousel.min.js:6:1986)
    at e.exports (project/node_modules/vue-carousel/dist/vue-carousel.min.js:6:3392)
    at Object.<anonymous> (project/node_modules/vue-carousel/dist/vue-carousel.min.js:6:947)
    at t (project/node_modules/vue-carousel/dist/vue-carousel.min.js:6:332)
    at VueComponent.a (project/node_modules/vue-carousel/dist/vue-carousel.min.js:6:786)
    at callHook (project/node_modules/vue/dist/vue.runtime.common.js:2663:21)
    at VueComponent.Vue._init (project/vue/dist/vue.runtime.common.js:4220:5)
    at new VueComponent (project/node_modules/vue/dist/vue.runtime.common.js:4394:12)
    at createComponentInstanceForVnode (project/node_modules/vue-server-renderer/build.js:6817:10)
```

**Comment by iamdubx** [comment] 2017-08-10 10:53
@dieguezz I am pretty sure you are not telling the whole picture. It has nothing with Nuxt version. To get rid of warning you need to load plugin on mounted. You will have warning 100% in other case.

**Comment by sainf** [comment] 2017-08-26 21:00
Hi.

Just tested with nuxt as it still gives errors, and it should give.. because it uses Browser only function like ( document and window )

To load the plugin in "mounted" is to bypass the server render, see: [https://nuxtjs.org/guide/plugins](url)

An easy solution is to use "no-ssr": [https://github.com/egoist/vue-no-ssr](url) and load the plugin as nuxt docs.

Of course all this solutions are not for server rendering, so seo will be hurt.

It would be nice to see this great plugin to work in full SSR.

**Comment by james2doyle** [comment] 2017-11-24 00:52
I think the issue is that `this.$isServer` is `undefined` during render in nuxt. Because the guard is `!this.$isServer`, the code in those blocks continues to run. I think an option would be to use `typeof(this.$isServer) !== 'undefined' && this.$isServer === true`.

I think the best option is to set `isServer` _as a prop_ with the default set to `false`. Then the user can decide what conditions they want to treat as "isServer".

**Comment by lanbau** [comment] 2018-01-02 07:14
hi i am also experience the same error as mentioned above.

**Comment by dfee** [comment] 2018-03-05 20:29
I initially missed @sainf's recommendation, but indeed the answer to this thread appears to be the following:

```js
// plugins/vue-carousel.js
import Vue from 'vue';
import VueCarousel from 'vue-carousel';

Vue.use(VueCarousel);
```

```js
// nuxt.config.js
{
...
  plugins: [ '~/plugins/vue-carousel' ],
...
}```

```js
// e.g. pages/index.vue
<template>
<no-ssr>
  <carousel>
    <slide v-for='i in 10' :key='i'>Slide {{ i }}</slide>
  </carousel>
</no-ssr>
</template>
```

A couple points – I didn't specify `ssr: false` in `nuxt.config.js` and that's because while it's true that `vue-carousel` *should not* be used in SSR mode, it actually needs to be wrapped in a `no-ssr` component which appears to take a higher precedence.

**Comment by natemate90** [comment] 2018-10-05 16:06
I added  `plugins: [{src: '~/plugins/vue-carousel.js', ssr: false}],` in `nuxt.config.js` to force nuxt not to use ssr on this component, nu need to use `<no-ssr>`

**Comment by amjadkhan896** [comment] 2019-01-24 13:39
I am having the same issue. Not working in SSR "npm run build" command

**Comment by quinnlangille** [comment] 2019-01-31 14:57
Hey @amjadkhan896, there are lots of potential solutions for SSR posted above ^. So many, that it actually warrants closing this issue. I'll flag it as a question for searchability, but this issue is definitely resolved :octocat:

**Closed by quinnlangille** 2019-01-31 14:57 UTC
Labels: bug, help wanted, need repro

**Comment by syamkumarkk** [comment] 2020-02-25 10:14
> I solved it by:
> 
> `// nuxt.config.js`
> 
> ```
> plugins: [{ src: '~/plugins/carousel', ssr: false }],
> ```
> 
> `// plugins/carousel.js`
> 
> ```
> import Vue from 'vue'
> import { Carousel, Slide } from 'vue-carousel'
> 
> Vue.component('carousel', Carousel)
> Vue.component('slide', Slide)
> ```
> 
> Hope it helps!

Its the solution for Nuxt.js ....

**Comment by Qvatra** [comment] 2021-07-06 11:48
there were 2 prs open for making ssr possible but issues were closed for both without merging... why is that?
https://github.com/SSENSE/vue-carousel/pull/577
https://github.com/SSENSE/vue-carousel/pull/459
