### ISSUE TITLE
perPage set 2.2 not work

### ISSUE THREAD

**Issue by maqunjing** [SSENSE/vue-carousel#101] opened 2017-12-06 06:46 UTC

**Comment by Loschcode** [comment] 2017-12-15 14:05
The perPage option doesn't work for me either

**Comment by quinnlangille** [comment] 2018-01-19 23:51
Hey @maqunjing @Loschcode, `perPage` is working fine on my end - could I get some additional details or a JS fiddle recreating the bug? Thanks!

**Comment by mydnic** [comment] 2018-02-01 19:00
not working for me either

**Comment by quinnlangille** [comment] 2018-02-01 19:56
@mydnic I'll investigate it laster this week and see if I can recreate - if you have any more details or examples of it happening feel free to post here

**Comment by mydnic** [comment] 2018-02-03 12:31
The second example (called "Responsive") on your website (https://ssense.github.io/vue-carousel/examples/) demonstrate the issue actually.
In the fiddle : https://jsfiddle.net/toddlawton/rvhxLdkq/?utm_source=website&utm_medium=embed&utm_campaign=rvhxLdkq

`:perPage="4"` but only 2 slides are displayed

**Comment by quinnlangille** [comment] 2018-02-04 18:20
Hmm good find, it seems that in the example `perPage` is being overwritten by `perPageCustom`. You can see it working as intended in this fiddle -> https://jsfiddle.net/sf8ugeLL/. 

I'll revise the example in the next update!

**Comment by mydnic** [comment] 2018-02-09 17:53
@quinnlangille The same thing but doing it this way:

https://jsfiddle.net/sf8ugeLL/1/

And the problem appears

I use back-end generated views with vuejs so I have this kind of code:

```<carousel :perPage="7">
                @foreach ($brands as $brand)
                    <slide>
                        <img src="{{ $brand->image }}" alt="{{ $brand->name }}">
                    </slide>
                @endforeach
            </carousel>```

Only 2 images are displayed per page

**Comment by crnkovic** [comment] 2018-02-16 13:50
I had the same issue, however calling prop `per-page` instead of `perPage` fixed the issue.

Example:

```html
<carousel :per-page="6">
    ...
</carousel>
```

**Comment by mydnic** [comment] 2018-02-16 14:00
@crnkovic I confirm it works that way :)
thanks!

**Comment by quinnlangille** [comment] 2018-02-16 15:33
Thanks for pointing that out, @crnkovic, I didn't even think to check.

As a side note - camelCase -> dash-case is actually already bundled into `v0.6.6`, which should be out shortly!

**Comment by quinnlangille** [comment] 2018-02-21 21:39
Hey guys, just release `v0.6.7` which addresses the camelCase bug, pull and test it out! Going to close this now, feel free to open a new issue if there are still any problems

**Closed by quinnlangille** 2018-02-21 21:39 UTC

**Comment by youssef-tharwat** [comment] 2019-04-04 21:16
> I had the same issue, however calling prop `per-page` instead of `perPage` fixed the issue.
> 
> Example:
> 
> ```
> <carousel :per-page="6">
>     ...
> </carousel>
> ```
> 
> Every prop should be converted from camelCase to dash-case, such as `paginationEnabled` to `pagination-enabled`.

This Worked for me too. Thank you

**Comment by JeRabix** [comment] 2019-10-04 12:44
not work for me)

> I had the same issue, however calling prop `per-page` instead of `perPage` fixed the issue.
> 
> Example:
> 
> ```
> <carousel :per-page="6">
>     ...
> </carousel>
> ```
> 
> Every prop should be converted from camelCase to dash-case, such as `paginationEnabled` to `pagination-enabled`.

**Comment by Eben-Hafkamp** [comment] 2021-01-14 23:24
@quinnlangille 
> As a side note - camelCase -> dash-case is actually already bundled into `v0.6.6`, which should be out shortly!

Sorry, on the npmjs page the latest version is listed as 0.18.0? I also ran into this camel vs kebab case issue and almost gave up before finding this ticket. What is the recommended way to install latest version?

**Comment by liebsen** [comment] 2023-02-04 14:05
you can always implement

			<carousel
				:per-page="1.1"
				:scroll-per-page="false"
