### ISSUE TITLE
Bug: Slide component does not load when carousel's parent component is imported 0.6.8

### ISSUE THREAD

**Issue by DavidVII** [SSENSE/vue-carousel#138] opened 2018-02-27 21:29 UTC
Hello, I ran into an odd issue where the Carousel doesn't display until I click on where the slide would be or trigger a pageChange by clicking on a pagination icon. Even stranger is that the elements are all there in the markup, but they won't display until i click in the general area of the slider.

This only seems to occur when I import the components into another component that is being imported as well.

```js
import Vue from 'vue'
import ProductOverview from './components/product-overview.vue'

const app = document.getElementById("app")

new vue({
  el: app,
  template: "<ProductOverview />",
  components: { ProductOverview }
})
```

```vue
<template>
<div class="product">
  <product-images></product-images>
  <product-form></product-form>
</div>
</template>

<script>
import ProductImages from "./product-images.vue";
import ProductForm from "./product-form.vue";

export default {
  components: {
    ProductImages,
    ProductForm
  }
};
</script>
  
```

```vue
<template>
  <carousel>
    <slide>
      <img src="https://placehold.it/600x400">
    </slide>
    <slide>
      <img src="https://placehold.it/600x400">
    </slide>
  </carousel>
</template>

<script>
import { Carousel, Slide } from "vue-carousel";

export default {
  components: {
    Carousel,
    Slide
  }
};
</script>
```

Here are some screenshots as well.

![initial-load](https://user-images.githubusercontent.com/504075/36755764-0dd53e76-1bc2-11e8-9b2d-8d1eb2fb6085.png)

I click on one of the pagination circles:

![after-click](https://user-images.githubusercontent.com/504075/36755782-144e4a72-1bc2-11e8-8d44-580ca213a8ef.png)

**Comment by quinnlangille** [comment] 2018-02-27 22:15
Hey @DavidVII, this was a new problem introduced in 0.6.8? If you roll back to 0.6.7 it's working? Your code looks fine, so perhaps you could link a JSfiddle or stackblitz with this happening so we can take a better look

**Comment by DavidVII** [comment] 2018-02-27 23:03
Hi @quinnlangille, I only heard about this library today and so I've only used 0.6.8. However, I tried using 0.6.8 and it seems to be happening there as well. I'll try and put together a JSfiddle, but the example above is all I've got. Not sure if it makes a difference, but I am using webpack.

**Comment by DavidVII** [comment] 2018-02-27 23:37
@quinnlangille it appears that the visibility and flex-basis styles on `.VueCarousel-inner` are failing to update when the component is rendered.

They load like this when the component renders:

`visibility: hidden` and `flex-basis: 0px`

Then after I click on the hidden element, they update to this:

visibility: visible` and `flex-basis: 522px`

Is there a way to trigger this update manually? I may just end up doing this when the component first mounts as a work around for now.

**Comment by quinnlangille** [comment] 2018-02-28 15:26
Hmm I'll try and recreate the issue on my local. Let me know if the on-mount quick-fix works and hopefully we'll get a more permanent solution soon.

**Comment by dougjuliao** [comment] 2018-03-02 19:03
Hi guys, i don't know if it will run to you, but i try a manual way for now:
In Carousel.vue 

Old
```vue
<div
        class="VueCarousel-inner"
        v-bind:style="`
          transform: translate3d(${currentOffset}px, 0, 0);
          transition: ${!dragging ? transitionStyle : 'none'};
          flex-basis: ${slideWidth}px;
          visibility: ${slideWidth ? 'visible' : 'hidden'};
          padding-left: ${padding}px;
          padding-right: ${padding}px;
        `"
      >
        <slot></slot>
      </div>
```
New
```vue
<div
        class="VueCarousel-inner"
        v-bind:style="`
          transform: translate3d(${currentOffset}px, 0, 0);
          transition: ${!dragging ? transitionStyle : 'none'};
          flex-basis: ${slideWidth <= 0 ? '100%' : slideWidth+'px'};
          visibility: visible;
          padding-left: ${padding}px;
          padding-right: ${padding}px;
        `"
      >
        <slot></slot>
      </div>
```
for a while it is working for me.

**Comment by DavidVII** [comment] 2018-03-13 23:46
Howdy, not sure if this affects things, but the carousel is in a modal. I imagine the carousel component can't calculate dimensions due to the modal being disabled by default.

For now, I'm still setting the flex basis and visibility manually.

**Comment by quinnlangille** [comment] 2018-03-14 23:33
@DavidVII Hmm I still can't seem to recreate this issue, is it occurring cross-browser?

**Comment by DavidVII** [comment] 2018-03-14 23:55
Chrome and Firefox both have this issue. Did you try rendering in a hidden modal then activating the modal?

**Comment by sohailalam2** [comment] 2018-04-18 14:30
Hi @quinnlangille any update on this? 

I am also facing the same issue... here is a snippet of my code - 

```html
<carousel :perPage="3" :navigationEnabled="true" :paginationEnabled="false">
    <slide v-for="(mySlide, i) in allSlides" :key="i">
        <MyComponent :key="i" :myData="mySlide"></MyComponent>
    </slide>
</carousel>
```

Where **MyComponent** is a VueJs component which contains the template and some business logic like click listeners etc.

**Comment by quinnlangille** [comment] 2018-04-18 14:57
Hey @sohailalam2, no progress on this currently. I think it may be related to #172 - if not directly related, it should be resolved by this as a side effect. I'm going to try and get this prioritized, so hopefully will have a fix in the near future!

**Comment by sohailalam2** [comment] 2018-04-18 15:25
Hi, @quinnlangille thanks for the update. Any comment about the ETA? 
We are kind of stuck because of this and cant release until this is resolved.

**Comment by quinnlangille** [comment] 2018-04-18 15:30
@sohailalam2 it's going to be a big fix, as adding the scoped slots will require rewiring how the carousel works. Hopefully something will come through in the next few weeks - If there is no traction from the community I'll work on a solution myself. 

If you end up resolving the issue on your end, feel free to make a PR here with the fix!

**Comment by nchlodzi** [comment] 2018-05-08 01:34
I run into similar issue while trying to use 3 slider components in one parent component.  My component looks like this:
![image](https://user-images.githubusercontent.com/16885110/39732107-b8d58990-526b-11e8-9dfb-39128f77e55b.png)
While page is loaded the first component with first set of tests are loaded correctly. But unfortunatly when i want to swich to other set of test ( by pressing button 2 or 3 ) there is nothing shown until i change the resolution of page but even then the look of the page is not what was set in styles and to add more the otheres compoennts now are not visible too. 

This is the picture taken just when swiching to other test component:
![image](https://user-images.githubusercontent.com/16885110/39732222-6e888896-526c-11e8-8dc6-2f87d362ab0e.png)


and this is when moving the resolution of page:

![image](https://user-images.githubusercontent.com/16885110/39732248-9bc2f3be-526c-11e8-944d-212e06d46eb1.png)



and going back to old tests component:

![image](https://user-images.githubusercontent.com/16885110/39732280-bcb3cbca-526c-11e8-895e-cdf27a082495.png)


I tried to set the style of VueCarousel-inner" to  visibility: visible; as was suggested above but still the effect was not what i wanted as you may see:

![image](https://user-images.githubusercontent.com/16885110/39732375-38a8f016-526d-11e8-8b4a-b33019ea98b3.png)

all my child tests components have similar code:
```
<template>
      <div class="article">
        <carousel class="summer" :perPageCustom="[[300, 1.5], [768, 3.15]]" :paginationEnabled="false" :minSwipeDistance="2" :scrollPerPage="false" :mouseDrag="true" :perPage=3>
          <slide class="boxSmall" v-for="(article, index) in articlesList.slice(0, 5)" :key="index">
            <a :href="'/testy-opon-letnich/' + article.slug">
              <div class="imgBoxSmall" >
                <img :src="article.thumbnail.article_list_medium.path">
              </div>
              <div class="textBoxSmall">
                <h1 class="titleName2"> {{ article.name }} </h1>
                <p class="articleText"> {{ article.seoDescription }} <span class="pageLink"> > </span></p>
              </div>
            </a>
          </slide>
        </carousel>
      </div>
</template>

```
```
<script>
  import { Carousel, Slide } from 'vue-carousel'
  export default {
    name: 'summer_main',
    components: {
      Carousel,
      Slide
    },
    data () {
      return {
        articlesList: []
      }
    },
     mounted () {
      let self = this
      $.getJSON('http://', function (data) {
        self.articlesList = data
      })
    }
  }
</script>
```
Only difference is in data for different tests

Part of my parent component: 
```
<div class="testsBox" v-show="selected == 1">
       <app-tests-winter></app-tests-winter>
</div>
<div class="testsBox" v-show="selected == 2">
      <app-tests-summer></app-tests-summer>
</div>
<div class="testsBox" v-show="selected == 3">
       <app-tests-all-seasons></app-tests-all-seasons>
</div>
```

```
<script>
  import TestsWinter from './tests_winter/winter_main.vue'
  import TestsSummer from './tests_summer/summer_main.vue'
  import TestsAllSeason from './tests_allSeason/allSeason_main.vue'
  export default {
    name: 'all-tests_main',
    components: {
      appTestsWinter: TestsWinter,
      appTestsSummer: TestsSummer,
      appTestsAllSeasons: TestsAllSeason
    },
    data () {
      return {
        selected: 1
      }
    }
  }
</script>
```

Hope there is solution for this problem becouse it's the best vue slider `i fund until now . I've spended last 5 days trying to find any working slider to my project and only this was working fine until i found this bug so hope there is some explanantion/solution for this slider compoenent behavior. Im using "vue-carousel": "^0.7.3". Best :)

**Comment by DavidVII** [comment] 2018-05-08 03:18
@nchlodzi this is indeed an unfortunate bug. I believe this may be solved with #172, but I'm not entirely sure.

I was able to get _some_ results with by setting the `VueCarousel-slide` style to this:

```
.VueCarousel-slide {
  visibility: visible;
  flex-basis: 100%;
  width: 100%;
}```

Try that instead of the `VueCarousel-inner`

It's a workaround, but it _should_ display the slides by default with that.

**Comment by quinnlangille** [comment] 2018-05-29 03:03
Hey guys, just merged in a recalculation of the carousel width provided by @nchlodzi - everything seems good on my end, but I was never able to recreate this bug on my own so I'm not the best judge 😅 Let me know if the problem is resolved and I will close this issue 🕵️

**Comment by nchlodzi** [comment] 2018-05-29 09:22
In my project vue-carousel in version 0.8.0 works great :) :) :). Hope it will work good for the others too :)

**Comment by carlosmtrinidad** [comment] 2018-05-30 04:50
In my project with vue carousel v0.8.0 doesn't work.
I use it inside a modal (Bootstrap v3.3.7) and it renders a carousel with pictures. The issue is with the rendering as it is not shown at the beginning and can't get the carousel width.

I solved it clicking the first dot on the navigation as soon as the modal is shown. I know its not a fix but it's working.
```
$('.VueCarousel-dot-container li:nth-child(1)').children().click();
this.$refs['carousel'].goToPage(0);
```
After that the carousel get the initial width and works perfectly.

**Comment by deakpal** [comment] 2018-09-04 18:58
I had the same problem, and my solution is:
`    mounted() {
      setTimeout(() => {
        this.$refs['carousel'].onResize();
        this.$refs['carousel'].goToPage(0);
      }, 200);
    }`

**Comment by BorysTyminski** [comment] 2019-01-02 04:48
I used @deakpal solution and actually it's working but for some reason now my pagination dots disapear. When I inspect console it added `display: none` to .VueCarousel-pagination element as inline style. Even when I overwrite it I can see only one dot and there is actually only 1 dot in DOM.

**Comment by quinnlangille** [comment] 2019-01-02 15:31
@BorysTyminski what version of the carousel are you using?

**Comment by BorysTyminski** [comment] 2019-01-02 20:15
@quinnlangille 
 
    "vue-carousel": "^0.10.0",

I don't know if it can be relevant but I display `<slide>` component in `v-for` loop:

             <div class="yacht__throw" v-if="imagesThrow.length > 1">
                     <carousel ref="carousel"
                              :perPage="1"
                              :autoplay="false"
                              :autoplayTimeout="3000"
                              :loop="true"
                              :navigationEnabled="true"
                              :paginationEnabled="true"
                              :paginationActiveColor="'#333'"
                              :paginationColor="'#d8d8d8'"
                              :scrollPerPage="false">
                        <slide v-for="n in imagesThrow" :key="n">
                            <img :src="n" alt="Rzut" class="img-fluid" />
                        </slide>
                    </carousel>
             </div>

and also I have in my script @deakpal solution:

        mounted() {
            eventBus.$on('resize::slider', () => {
                this.$refs['carousel'].onResize();
                this.$refs['carousel'].goToPage(0);
            });
        },

Result is that it for some reason adds `style="display:none"` to `.vueCarousel-pagination` div. When I overwrite this inline style to `display:block` this doesn't help because in DOM inside pagination list there is only one dot:

![image](https://user-images.githubusercontent.com/40339232/50610351-f9e58380-0ed2-11e9-9478-438d89ab6109.png)

![image](https://user-images.githubusercontent.com/40339232/50610446-4d57d180-0ed3-11e9-9b90-6812e2de7e9e.png)

**Comment by quinnlangille** [comment] 2019-01-02 23:19
👍 All good! I'm going to close this issue, as I think it and it's edge cases have been resolved by recent updates. 

Anyone still having any issues regarding this, feel free to post after I've closed or open a new issue :octocat:

**Closed by quinnlangille** 2019-01-02 23:19 UTC
Labels: bug, help wanted

**Comment by fattchris** [comment] 2019-01-15 03:09
I can confirm that with version 0.17.0, placing the carousel in a Bootstrap Modal still exhibits this bug. I do not currently have a workaround, and the CSS "work arounds" listed here do not work.

**Comment by smakman** [comment] 2019-01-22 12:30
I trigger a window resize once the carousel is visible: 

```js
watch (carouselVisible) {
  if (carouselVisible) {
    Vue.nextTick(() => window.dispatchEvent(new Event('resize')))
  }
}
```

**Comment by aligilan** [comment] 2019-08-23 07:42
### you can solve vue-carousel show problem in vue-modal, in this way:
carousel component needs refresh, after modal shown.
1-with modal event: `@shown`, can trigger when carousel refresh.
2-when component `key` changes, component will refresh.
so:

```
...
<b-modal @shown="refreshCarousel()">
    <carousel :key="frequency">
...

data(){
    return {
        frequency: 1,
    },
    methods: {
        refreshCarousel(){
            this.frequency++
        }
    }
},
```
Hope it will be useful.

**Comment by dhaval-dignizant** [comment] 2019-10-15 13:48
i'm using collapse inside  Carousel default tab working. when I open the second tab slider not work. after I click on second tab content it works.

**Comment by SuAnita520** [comment] 2020-05-01 14:43
> I trigger a window resize once the carousel is visible:
> 
> ```js
> watch (carouselVisible) {
>   if (carouselVisible) {
>     Vue.nextTick(() => window.dispatchEvent(new Event('resize')))
>   }
> }
> ```

Yeah, you are right. Currently, in 2020, I have the same issue. These slides component only get triggered to display when window size changed.

**Comment by colesnic89** [comment] 2020-06-11 07:06
> @quinnlangille it appears that the visibility and flex-basis styles on `.VueCarousel-inner` are failing to update when the component is rendered.
> 
> They load like this when the component renders:
> 
> `visibility: hidden` and `flex-basis: 0px`
> 
> Then after I click on the hidden element, they update to this:
> 
> `visibility: visible` and `flex-basis: 522px`
> 
> Is there a way to trigger this update manually? I may just end up doing this when the component first mounts as a work around for now.

I have the same issue for version v0.18.0-alpha

**Comment by heshamelmasry77** [comment] 2020-12-01 19:44
I still have the same issue :(, please let's reopen this.

**Comment by murtazasultani** [comment] 2021-01-30 21:49
still have the same issue

**Comment by jamshidhashimi** [comment] 2021-02-01 18:08
In `"vue-carousel": "^0.18.0",` this worked for me:

```
$('#myModal').on('shown.bs.modal', function () {
    Vue.nextTick(() => window.dispatchEvent(new Event('resize')));
})
```
