### ISSUE TITLE
:navigationEnabled="true" not working

### ISSUE THREAD

**Issue by iamdubx** [SSENSE/vue-carousel#72] opened 2017-08-07 19:59 UTC
I can enable navigation. Adding `:navigationEnabled="true"` to carousel doesn't effect anything.
Using with blank webpack starter.

**Comment by cviebrock** [comment] 2017-09-01 18:41
Same here.

**Comment by lhovee** [comment] 2017-09-02 21:22
@iamdubx @cviebrock I'm not sure if this fixes the issue but I believe it's supposed to be `:navigation-enabled=true`. 
Another thought is I thought my navigation was broken until I realized the carousel was too wide and pushing my nav icons off screen.  Setting a max-width on your carousel container might be necessary.

**Comment by chrisribe** [comment] 2017-10-24 20:10
@lhovee Thanks fixed it for me the param seems to be incorrect in the documentation.

**Comment by chrisribe** [comment] 2017-10-25 13:36
Please fix the jsfiddle example:
<script async src="//jsfiddle.net/toddlawton/46wegz8a/embed/result,js/"></script>

Odd both methods of using the param works under jsfiddle (maybe caused by babel?)
Chris

**Comment by quinnlangille** [comment] 2018-02-22 23:39
Going to update the documentation with the proper kebab-case props now. Closing this issue, feel free to open another issue if you have any questions!

**Closed by quinnlangille** 2018-02-22 23:39 UTC

**Comment by devWaleed** [comment] 2019-02-26 11:23
I am still having this issue. :navigation-enabled="true" or :navigationEnabled="true" is not working.

**Comment by simbilim** [comment] 2019-03-16 12:15
@devWaleed have you found a way to fix the issue?

**Comment by heavensloop** [comment] 2019-10-12 17:42
> @iamdubx @cviebrock I'm not sure if this fixes the issue but I believe it's supposed to be `:navigation-enabled=true`.
> Another thought is I thought my navigation was broken until I realized the carousel was too wide and pushing my nav icons off screen. Setting a max-width on your carousel container might be necessary.

This and the following css helped to reveal the links: 

```
.VueCarousel-navigation-button {
                position: relative;
}
```

**Comment by daviraquel** [comment] 2022-06-21 18:18
I was having the same issue. Prop case style didn't work, suggested css didn't work either but made me take the same path. This one did the trick:

.VueCarousel-navigation-prev,
.VueCarousel-navigation-next {
  transform: translateY(-50%) !important;
}

It seems the original transform properties for these classes, which also contained a translateX() were moving both buttons away from the screen.

They're also black with transparent background by default wich initially made me think they were not showing because the page was dark.
