### ISSUE TITLE
Slice not working with Select element html

### ISSUE THREAD

**Issue by tranvannhat** [SSENSE/vue-carousel#319] opened 2018-11-22 02:13 UTC
`<slide v-for="item in listTestProduct" :key="item.id">
          <select :class="[$style.customSelect, $style.customSelectSm]">
              <option selected>S</option>
              <option value="1">M</option>
              <option value="2">XL</option>
              <option value="3">XXL</option>
            </select>
      </slide>`
when use Select option cannot drag and drop slice

**Comment by quinnlangille** [comment] 2018-11-22 16:58
Hey @tranvannhat, not 100% what the issue is here. Going to close this, as it's ambigious. If you haven't resolves on your end please reopen with an issue template! Thanks :octocat:

**Closed by quinnlangille** 2018-11-22 16:58 UTC
