### ISSUE TITLE
Wrong position navigation/pagination in the version 0.10.0?

### ISSUE THREAD

**Issue by jkwasniak** [SSENSE/vue-carousel#255] opened 2018-08-06 09:15 UTC
after first init call i see:
- wrong position navigation:
  - navigationPrevLabel ist active, even first element
  - navigationNextLabel ist inactive, even first element and there are other elements
- wrong position pagination: 
  - last pagination dot ist active, even first element

In Version 0.9.0 everything worked correctly.
```
      <carousel
        :per-page-custom="[[540, 2], [720, 2], [960, 3], [1140, 3]]"
        :navigation-enabled="true"
        pagination-active-color="#c60039">
        <slide
          v-for="document in documentData"
          :key="document.id">
          <div
            class="card card-pass mx-1 border-0">
            <a
              :href="document.uri"
              target="_blank">
              <img
                :src="document.thumbUri"
                class="card-img-top img-fluid img-thumbnail p-1 w-100"
                alt="Dokumentbild"></a>
            <div class="card-body">
              <div class="text-muted">{{ document.documentDate | date }}</div>
              <p class="card-title text-primary">{{ document.title }} ({{ document.pages }} S.)</p>
            </div>
          </div>
        </slide>
      </carousel>
```

**Comment by quinnlangille** [comment] 2018-08-09 16:45
Hey @jkwasniak, I'm not seeing this happening on my end. Care to send a JS fiddle or repo I can clone and test? Thanks - will flag accordingly now.

**Comment by codigovision** [comment] 2018-08-15 16:17
I experienced the same issue with version 0.10.0 on vue 2.5.2. Downgraded to 0.9.0 as suggested and it's working.

I'm using the global setup:

import VueCarousel from 'vue-carousel'
Vue.use(VueCarousel)

And my test was just a basic carousel with 2 slides, one per page.

**Comment by quinnlangille** [comment] 2018-09-18 18:06
Has this been resolved with the latest release? I'm unable to reproduce

**Closed** 2018-11-09 19:17 UTC
Labels: need repro
